### ISSUE TITLE
[not bug] How to run mprof if I have 2 versions of python

### ISSUE THREAD

**Issue by vuklip** [fabianp/memory_profiler#115]
Hello. Sorry if this question is silly or strange but I couldn't Google this question.
On my mac I have pre-installed python 2.7.10 and installed by myself 3.5.1.

When I use `mprof run mem_test.py` it runs on 2.7. How can I run it on 3th version? 
I tried `python3 -m mprof run mem_test.py` , but `/Library/Frameworks/Python.framework/Versions/3.5/bin/python3: No module named mprof`

regards, Artem

**Comment by superbobry** [comment]
Python2 and Python3 packages are independent, so you need to install `memory_profiler` for Python3 as well

```
$ python3 -m pip install memory_profiler
```

Then `python -m mprof` should work fine.

**Comment by vuklip** [comment]
Of course I did it 😸 

```
$ python -m pip show memory-profiler
---
Metadata-Version: 2.0
Name: memory-profiler
Version: 0.41
...
Location: /Library/Python/2.7/site-packages


$ python3 -m pip show memory-profiler
---
Metadata-Version: 1.1
Name: memory-profiler
Version: 0.41
...
Location: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages
```

but

```bush
$ python -m mprof
/usr/bin/python: No module named mprof

$ python3 -m mprof
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3: No module named mprof
```

and after that

```
$  mprof run memory.py
mprof: Sampling memory every 0.1s
running as a Python program...
```
it works...

**Comment by fabianp** [comment]
So problem solved? Thanks @superbobry for the response

**Comment by vuklip** [comment]
@fabianp unfortunately no 😭 
By default it runs by 2.7...

**Comment by fabianp** [comment]
OK. The [mprof program](https://github.com/fabianp/memory_profiler/blob/master/mprof) will choose the default python (as you can see in the first line). I suppose you can either change that first and hardcode the desired python or run it as

```python3 /path/to/mprof run mem_test.py```

hope that helps

**Comment by superbobry** [comment]
This could be fixed by making `memory_profiler` a module and converting `mprof` to `__main__`.

**Comment by vuklip** [comment]
@fabianp 👍 
How did not I think of that... I just did `git clone` and run it like you say. Thx.

@superbobry thx you too 😉

**Comment by dizcza** [comment]
`$ python3.6 /Library/Frameworks/Python.framework/Versions/3.6/bin/mprof run load.py`
still runs with python2.7 and I don't know why.
@superbobry , could you clarify how to make `memory_profiler` a module and convert `mprof` to `__main__`?

**Comment by superbobry** [comment]
@dizczad This is probably to big of a change, but essentially you need to 

1. Create a new directory named `memory_profiler`
2. Move `memory_profiler.py` to `memory_profiler/__init__.py`
3. Move `mprof` to `memory_profiler/__main__.py`

After that you should be able to run `mprof` via `python -m memory_profiler`.

I think in your case `mprof` should use the Python you're calling it with. Could you double-check that you're running under 2.7? If yes, edit the first line in `mprof` to point to your your Python3.6 binary.
