### ISSUE TITLE
Graph plotting to shell/terminal console

### ISSUE THREAD

**Issue by drtrigon** [fabianp/memory_profiler#121]
I am using mprof on travis-ci. On travis It's not possible to display graphical output and thus `mprof plot` using matplotlib does not work.

Thanks to the simple format used by the `.dat` files, their content can directly be feed to gnuplot (using `set terminal dumb`). This is what I am doing currently and it works well.

Therefore I would like to propose to either implement plotting to shell/terminal console through the `mprof plot` command using gnuplot or any equivalent method (see e.g. http://stackoverflow.com/questions/123378/command-line-unix-ascii-based-charting-plotting-tool, http://stackoverflow.com/questions/20295646/python-ascii-plots-in-terminal) or to make sure not to change the `.dat` file format (for all times) in order to preserve the compatibility to gnuplot, as it is currently.

May be it would be useful to document how to use gnuplot to plot the `*.dat` files.

**Comment by fabianp** [comment]
Note that you can plot using matplotlib without a terminal by enforcing matplotlib to use the Agg backend (e.g. [like this](http://matplotlib.org/faq/howto_faq.html#matplotlib-in-a-web-application-server)). I would gladly accept a patch that forces matplotlib to use this backed, for example with a command line flag --backend Agg

**Comment by drtrigon** [comment]
This allows to save to an image file - but this does not help in displaying the plot (or the image file) in a text console.

**Comment by rth** [comment]
With PR #150, one should also be able to do this with,
```
mprof plot --backend <backend>
```
where `<backend>` is a ascii backend for matplotlib. I tried a couple and has not been able to make it work so far: with [itermplot](https://github.com/daleroberts/itermplot) I hit https://github.com/daleroberts/itermplot/issues/10 and [matascii](https://github.com/domitry/matascii) is outdated and doesn't support Python 3, but this should eventually work...
