### ISSUE TITLE
ImportError: cannot import name lru_cache

### ISSUE THREAD

**Issue by acs** [fabianp/memory_profiler#143]
Trying to profile a python3 application I get the error:

```
mprof: Sampling memory every 0.1s
Traceback (most recent call last):
  File "./p2o.py", line 31, in <module>
....
ImportError: cannot import name lru_cache

```
But using the application directly it works perfectly.

mprof has been installed with: 

`sudo pip3  install memory_profiler`

**Comment by superbobry** [comment]
Could you do `which mprof` and post the output here? It'd also be useful to see the whole stacktrace, i.e. the line causing the `ImportError`.

**Comment by acs** [comment]
```
(acs@dellx) ~ $ which mprof
/usr/local/bin/mprof

```

The complete stracktrace:

```
(acs@dellx) (master $% u=) ~/devel/GrimoireELK/utils $ mprof run ./p2o.py git https://github.com/grimoirelab/perceval
mprof: Sampling memory every 0.1s
Traceback (most recent call last):
  File "./p2o.py", line 31, in <module>
    from grimoire_elk.arthur import feed_backend, enrich_backend
  File "/home/acs/devel/GrimoireELK/utils/grimoire_elk/arthur.py", line 35, in <module>
    from .utils import get_elastic
  File "/home/acs/devel/GrimoireELK/utils/grimoire_elk/utils.py", line 61, in <module>
    from .elk.askbot import AskbotEnrich
  File "/home/acs/devel/GrimoireELK/utils/grimoire_elk/elk/askbot.py", line 32, in <module>
    from .enrich import Enrich, metadata
  File "/home/acs/devel/GrimoireELK/utils/grimoire_elk/elk/enrich.py", line 37, in <module>
    from functools import lru_cache
ImportError: cannot import name lru_cache

```

All the code is open source and can be accessed in:

https://github.com/grimoirelab/GrimoireELK/blob/master/grimoire_elk/elk/enrich.py#L37

Thanks you very much @superbobry We are having issues executing this library in a threaded application which starts using too much memory after some time (0.5h) of execution.

**Comment by acs** [comment]
I think I have found a workaround for this:

```
(acs@dellx) (master $% u=) ~/devel/GrimoireELK/utils $ mprof run python3 ./p2o.py git https://github.com/grimoirelab/perceval
....
```

For some reason when executing "./p2o.py" mprof with the run command, it uses python2 for doing it. 

This problem also affects the sample tutorial at:

http://fa.bianp.net/blog/2014/plot-memory-usage-as-a-function-of-time/

Am I doing something wrong? I am using just python3 env for using mprof.

**Comment by superbobry** [comment]
Thanks for the detailed reply. I think the reason for the behaviour you're seeing is in the [shebang](https://github.com/fabianp/memory_profiler/blob/master/mprof#L1) of `mprof`:

```python
#! /usr/bin/env python
```

which in your case points to Python2.X. [PEP-394](https://www.python.org/dev/peps/pep-0394/) requires Python3.X binaries to have the 3 suffix, so I think we should update `mprof`, since it doesn't run under 2.X.

What do you think @fabianp?

**Comment by fabianp** [comment]
Sounds good to me. So the proposed change is to change the shebang line to 

#!/usr/bin/env python3

?

**Comment by acs** [comment]
Just as a quick note, in my installed mprof I have:

```
(acs@dellx) (master *$% u=) ~/devel/mordred $ vi /usr/local/bin/mprof 
#!/usr/bin/python3

import glob
...
```
so apparently it is using python3. The issue seems to be related with how "run" command executes the python program after it.

**Comment by superbobry** [comment]
Oh, okay, it's more subtle: [this](https://github.com/fabianp/memory_profiler/blob/master/mprof#L222) line should be using `sys.executable` instead of hardcoded `python`.

As for the shebang, the transformation looks very magical. Maybe it's some setuptools/distutils magic...
