### ISSUE TITLE
mprof does not work with @profile in python3

### ISSUE THREAD

**Issue by acs** [fabianp/memory_profiler#144]
According to:

https://github.com/fabianp/memory_profiler/blame/master/README.rst#L153

if you want that the timestamps for function calls are recorded, you don't need to import the profile decorator from memory_profiler, you need to comment out from your script the line:

`# from memory_profiler import profile
`
But if I do that following the tutorial at: http://fa.bianp.net/blog/2014/plot-memory-usage-as-a-function-of-time/

```
(acs@dellx) /tmp $ mprof run test1.py 
mprof: Sampling memory every 0.1s
Traceback (most recent call last):
  File "test1.py", line 7, in <module>
    @profile
NameError: name 'profile' is not defined

```

And if I import profile with "from memory_profiler import profile" there are no data about functions calls in the plot.

**Comment by acs** [comment]
After playing a bit with:

(acs@dellx) /tmp $ mprof run --python python3 test1.py 

you get the timestamps! So maybe the documentation should be updated. 

'--python' run option does the trick. And you need to force "python3" after run, because it not, run uses the default python env which in my case is python2.

**Comment by fabianp** [comment]
thanks @acs ! I just pushed the fix pointed out by @superbobry in 6b7335053d16c4d40b626d4d306704538f1f885b , that is, to use sys.executable instead of just "python"

Please let me know if that solves the issue for you.

**Comment by fabianp** [comment]
(I made a new release, so you should just be able to update with ```pip install -U memory_profiler```)

**Comment by bamal** [comment]
I have the same issue too and it has not been solved @fabianp  (although I updated the new release) !
```  File "/home_sq/aboukhdhir/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1491, in run_script
pkg_resources.ResolutionError: No script named 'mprof'
```

**Comment by acs** [comment]
```
(acs@dellx) ~ $ sudo pip3 install -U memory_profiler
....
Successfully installed memory-profiler-0.46
(acs@dellx) ~/devel/python-memory $ mprof run --python surprise.py 
mprof: Sampling memory every 0.1s
running as a Python program...
/usr/bin/python: No module named memory_profiler
(acs@dellx) ~/devel/python-memory $ mprof run --python python3 surprise.py 
mprof: Sampling memory every 0.1s
running as a Python program...
```

So it has the same behavior that 0.45 version.

**Comment by bamal** [comment]
I have just replaced the file `mprof` in `anaconda/bin` then the profiling worked !

Thanks !

**Comment by fabianp** [comment]
There was still a hardcoded "python" that @superbobry spotted. I made a new release with this fix. It should solve the problem. Please let me know how it goes.

**Comment by vi3mool** [comment]
I install memory_profiler via pip and try using mprof. But get the following error:
-mprof is not recognised as an internal or external command.
any work around

**Comment by tilmanbeck** [comment]
Hi,
I had the same problem when using an virtualenv (which had python3 as python interpreter set). I use memory_profiler version `0.47`.
Without the use of above mentioned `--python python3` by @acs :
```shell
(venv) user@host:~/Code$ mprof run run.py config.json 
mprof: Sampling memory every 0.1s
Traceback (most recent call last):
  File "run.py", line 55, in <module>
    @profile
NameError: name 'profile' is not defined
```
Then I tried to force the use of my virtualenv and got this error:
```shell
(venv) user@host:~/Development/hiwi/document-selection/Code$ mprof run --python venv/bin/python run.py resources/strat_xmeans.json 
mprof: Sampling memory every 0.1s
running as a Python program...
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".../venv/lib/python3.5/site-packages/memory_profiler.py", line 1199, in <module>
    exec_with_profiler(script_filename, prof, options.backend)
  File ".../venv/lib/python3.5/site-packages/memory_profiler.py", line 1119, in exec_with_profiler
    exec(compile(f.read(), filename, 'exec'), ns, ns)
  File ".../venv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 40: invalid start byte
```
Using `--python python3` worked, though. Do you an idea why `mprof` is not using the activated virtualenv?
