### ISSUE TITLE
change the default .dat file for generating output

### ISSUE THREAD

**Issue by bamal** [fabianp/memory_profiler#145]
Can I change the default .dat(currently taken as the latest one) file such that I can specify the filename used to generate the output plot ?

**Comment by fabianp** [comment]
Hi there!. You should be able to achieve this with ```mprof plot file.dat``` , where file.dat is the one you want to use to generate the plot. Admittedly the documentation was not great and I just updated it 962ae2a5a2fb97dcd10d47be072887ce13abbced
