### ISSUE TITLE
Segment fault in PyObject_Hash() when using memory_profiler

### ISSUE THREAD

**Issue by TaoLv** [fabianp/memory_profiler#159]
Hi,

I just write a python object type with those C/C++ extensions of CPython. It's something like a simplefied numpy. But when I try to profile the momery cost of this type and its APIs, there is a segment fault occured in PyObject_Hash(). The hash funtion has already been implemented for the type.

Logs as below:
```
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/python2.7...Reading symbols from /usr/bin/python2.7...(no debugging symbols found)...done.
(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 833]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
Core was generated by `python -m memory_profiler test_mklndarray.py'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f47a5cc70e9 in PyObject_Hash () from /usr/lib64/libpython2.7.so.1.0
Missing separate debuginfos, use: debuginfo-install python-2.7.5-48.el7.x86_64
```

Any idea or suggestion is very appreciated.

**Comment by TaoLv** [comment]
It is solved. A tuple for shape info is passed from python code to C code and the tuple object is released by Py_XDECREF incorrectly. So when call hash() on frame.f_code object, a segment fault will be triggered when compute the hash value of frame.f_code.co_consts. Since con_consts contains a member with refcnt=0.

**Comment by fabianp** [comment]
Thanks for the report. Do you think there's something that should be
changed in memory profiler?

**Comment by TaoLv** [comment]
Sorry for the late reply. Question above has nothing to do with memory_profiler. Thanks for your greate effort on this very useful tool.
