### ISSUE TITLE
Documentation is outdated (profile.timestamp)

### ISSUE THREAD

**Issue by aynroot** [fabianp/memory_profiler#90]
Hi!

The deocumentation is outdated in "Executing external scripts" section.
When it comes to timestamps there is a piece of code under "It is also possible to timestamp a portion of code using a context manager like this:" line. It is not working in the last version of memory_profiler.

Is there a possibility to still add custom timestamps and see plots like [here](https://github.com/scikit-learn/scikit-learn/pull/2248)?

**Comment by fabianp** [comment]
Thanks for the report! I'll take a look into this this week.

**Comment by bennlich** [comment]
Hey @fabianp . Did you ever get to look at this? When I do `profile.timestamp` I get: `AttributeError: 'function' object has no attribute 'timestamp'`

**Comment by bennlich** [comment]
Oh! It looks like you just can't use profile.timestamp after `from memory_profiler import profile`. I deleted my import statements and `mprof run –python <script>` works as documented.

@aynroot you can use the `mprof` command to generate plots like those you linked to

**Comment by fabianp** [comment]
Hi, sorry for not being very reactive on this and thanks both for your input. I've removed the outdated line from the documentation, as @bennlich mentioned the prefered way is to call mprof.
